"use client"

import { createContext, useContext, useState, type ReactNode, useEffect } from "react"

export type Language = "en" | "hi" | "mr" | "ta" | "te" | "bn" | "gu" | "kn"
export type UserRole = "grocer" | "buyer" | null

export interface User {
  id: string
  name: string
  phone: string
  role: UserRole
  language: Language
  badges: Badge[]
  points: number
  itemsSold: number
  itemsBought: number
  foodSaved: number // in kg
  createdAt: Date
}

export interface Badge {
  id: string
  name: string
  nameKey: string
  description: string
  descriptionKey: string
  icon: string
  earnedAt?: Date
  requirement: number
  type: "sold" | "bought" | "saved" | "streak"
}

export interface FruitListing {
  id: string
  grocerId: string
  grocerName: string
  grocerPhone: string
  fruitName: string
  fruitNameKey: string
  condition: string
  conditionKey: string
  recommendedPrice: number
  finalPrice: number
  originalPrice: number
  quantity: string
  unit: string
  imageUrl: string
  bestFor: string[]
  bestForKeys: string[]
  expiresIn: string
  createdAt: Date
  status: "active" | "sold" | "expired"
}

interface AppContextType {
  language: Language
  setLanguage: (lang: Language) => void
  user: User | null
  setUser: (user: User | null) => void
  listings: FruitListing[]
  addListing: (listing: FruitListing) => void
  updateListing: (id: string, updates: Partial<FruitListing>) => void
  purchaseListing: (listingId: string) => void
  t: (key: string) => string
  currentStep: "language" | "login" | "role" | "dashboard"
  setCurrentStep: (step: "language" | "login" | "role" | "dashboard") => void
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    appName: "TerraLoop",
    tagline: "Save Food, Save Money, Save Earth",
    welcomeMessage: "Welcome to TerraLoop",
    selectLanguage: "Select Your Preferred Language",
    continue: "Continue",
    back: "Back",
    submit: "Submit",
    cancel: "Cancel",
    save: "Save",

    // Login
    loginTitle: "Join the Movement",
    loginSubtitle: "Help reduce food waste in your community",
    enterName: "Enter your name",
    enterPhone: "Enter your phone number",
    namePlaceholder: "Your full name",
    phonePlaceholder: "10-digit mobile number",

    // Role Selection
    selectRole: "How would you like to use TerraLoop?",
    iAmGrocer: "I'm a Grocer",
    iAmBuyer: "I'm a Buyer",
    grocerDesc: "List rescue deals and save food from waste",
    buyerDesc: "Find great deals on fresh produce nearby",

    // Grocer Dashboard
    grocerDashboard: "Grocer Dashboard",
    addNewDeal: "Add Rescue Deal",
    myListings: "My Listings",
    takePhoto: "Take or Upload Photo",
    analyzing: "AI is analyzing your fruit...",
    fruitDetected: "Fruit Detected",
    recommendedPrice: "AI Recommended Price",
    adjustPrice: "Adjust Price",
    publishDeal: "Publish Rescue Deal",
    quantity: "Quantity",
    bestFor: "Best For",
    expiresIn: "Best Before",
    condition: "Condition",
    originalPrice: "Original Price",
    yourPrice: "Your Price",
    discount: "Discount",

    // Buyer Dashboard
    buyerDashboard: "Fresh Deals Nearby",
    availableDeals: "Available Rescue Deals",
    noDeals: "No deals available right now",
    buyNow: "Rescue Now",
    viewDetails: "View Details",
    contactGrocer: "Contact Grocer",

    // Gamification
    yourBadges: "Your Badges",
    yourProgress: "Your Progress",
    pointsEarned: "Points Earned",
    itemsSold: "Items Sold",
    itemsBought: "Items Rescued",
    foodSaved: "Food Saved",
    level: "Level",
    nextBadge: "Next Badge",

    // Badges
    badgeFirstSale: "First Sale",
    badgeFirstSaleDesc: "Sold your first rescue item",
    badgeFoodHero: "Food Hero",
    badgeFoodHeroDesc: "Saved 10kg of food from waste",
    badgeRescueChamp: "Rescue Champion",
    badgeRescueChampDesc: "Rescued 25 items",
    badgeEcoWarrior: "Eco Warrior",
    badgeEcoWarriorDesc: "Saved 50kg of food",
    badgeSuperSeller: "Super Seller",
    badgeSuperSellerDesc: "Sold 50 rescue items",
    badgeStreakMaster: "Streak Master",
    badgeStreakMasterDesc: "7-day active streak",

    // Fruits
    mango: "Mango",
    banana: "Banana",
    apple: "Apple",
    orange: "Orange",
    papaya: "Papaya",
    grapes: "Grapes",
    watermelon: "Watermelon",
    pomegranate: "Pomegranate",
    guava: "Guava",
    pineapple: "Pineapple",

    // Conditions
    ripe: "Ripe & Sweet",
    veryRipe: "Very Ripe",
    slightlyOverripe: "Slightly Overripe",
    perfectForShakes: "Perfect for Shakes",

    // Best For
    shakes: "Shakes",
    smoothies: "Smoothies",
    cooking: "Cooking",
    eating: "Fresh Eating",
    juice: "Fresh Juice",
    desserts: "Desserts",
    jam: "Jam Making",

    // Time
    hours: "hours",
    today: "Today",
    tomorrow: "Tomorrow",

    // Stats
    kgSaved: "kg saved",
    dealsCompleted: "deals completed",
    happyCustomers: "happy customers",
    co2Reduced: "kg CO₂ reduced",

    // Messages
    dealPublished: "Your rescue deal is now live!",
    thankYou: "Thank you for saving food!",

    // Profile
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    editProfile: "Edit Profile",
  },
  hi: {
    // General
    appName: "टेरालूप",
    tagline: "खाना बचाएं, पैसे बचाएं, पृथ्वी बचाएं",
    welcomeMessage: "टेरालूप में आपका स्वागत है",
    selectLanguage: "अपनी पसंदीदा भाषा चुनें",
    continue: "जारी रखें",
    back: "वापस",
    submit: "जमा करें",
    cancel: "रद्द करें",
    save: "सहेजें",

    // Login
    loginTitle: "आंदोलन में शामिल हों",
    loginSubtitle: "अपने समुदाय में खाद्य अपशिष्ट को कम करने में मदद करें",
    enterName: "अपना नाम दर्ज करें",
    enterPhone: "अपना फोन नंबर दर्ज करें",
    namePlaceholder: "आपका पूरा नाम",
    phonePlaceholder: "10 अंकों का मोबाइल नंबर",

    // Role Selection
    selectRole: "आप टेरालूप का उपयोग कैसे करना चाहेंगे?",
    iAmGrocer: "मैं दुकानदार हूं",
    iAmBuyer: "मैं खरीदार हूं",
    grocerDesc: "रेस्क्यू डील लिस्ट करें और खाना बर्बाद होने से बचाएं",
    buyerDesc: "पास में ताजा उत्पादों पर शानदार डील पाएं",

    // Grocer Dashboard
    grocerDashboard: "दुकानदार डैशबोर्ड",
    addNewDeal: "रेस्क्यू डील जोड़ें",
    myListings: "मेरी लिस्टिंग",
    takePhoto: "फोटो लें या अपलोड करें",
    analyzing: "AI आपके फल का विश्लेषण कर रहा है...",
    fruitDetected: "फल पहचाना गया",
    recommendedPrice: "AI अनुशंसित मूल्य",
    adjustPrice: "मूल्य समायोजित करें",
    publishDeal: "रेस्क्यू डील प्रकाशित करें",
    quantity: "मात्रा",
    bestFor: "सबसे अच्छा के लिए",
    expiresIn: "इससे पहले सबसे अच्छा",
    condition: "स्थिति",
    originalPrice: "मूल मूल्य",
    yourPrice: "आपका मूल्य",
    discount: "छूट",

    // Buyer Dashboard
    buyerDashboard: "पास में ताजा डील",
    availableDeals: "उपलब्ध रेस्क्यू डील",
    noDeals: "अभी कोई डील उपलब्ध नहीं",
    buyNow: "अभी रेस्क्यू करें",
    viewDetails: "विवरण देखें",
    contactGrocer: "दुकानदार से संपर्क करें",

    // Gamification
    yourBadges: "आपके बैज",
    yourProgress: "आपकी प्रगति",
    pointsEarned: "अर्जित अंक",
    itemsSold: "बेची गई वस्तुएं",
    itemsBought: "रेस्क्यू की गई वस्तुएं",
    foodSaved: "बचाया गया खाना",
    level: "स्तर",
    nextBadge: "अगला बैज",

    // Badges
    badgeFirstSale: "पहली बिक्री",
    badgeFirstSaleDesc: "अपनी पहली रेस्क्यू वस्तु बेची",
    badgeFoodHero: "फूड हीरो",
    badgeFoodHeroDesc: "10 किलो खाना बर्बादी से बचाया",
    badgeRescueChamp: "रेस्क्यू चैंपियन",
    badgeRescueChampDesc: "25 वस्तुएं रेस्क्यू कीं",
    badgeEcoWarrior: "इको वॉरियर",
    badgeEcoWarriorDesc: "50 किलो खाना बचाया",
    badgeSuperSeller: "सुपर सेलर",
    badgeSuperSellerDesc: "50 रेस्क्यू आइटम बेचे",
    badgeStreakMaster: "स्ट्रीक मास्टर",
    badgeStreakMasterDesc: "7 दिन की सक्रिय स्ट्रीक",

    // Fruits
    mango: "आम",
    banana: "केला",
    apple: "सेब",
    orange: "संतरा",
    papaya: "पपीता",
    grapes: "अंगूर",
    watermelon: "तरबूज",
    pomegranate: "अनार",
    guava: "अमरूद",
    pineapple: "अनानास",

    // Conditions
    ripe: "पका और मीठा",
    veryRipe: "बहुत पका",
    slightlyOverripe: "थोड़ा अधिक पका",
    perfectForShakes: "शेक के लिए उत्तम",

    // Best For
    shakes: "शेक",
    smoothies: "स्मूदी",
    cooking: "खाना बनाना",
    eating: "ताजा खाना",
    juice: "ताजा जूस",
    desserts: "मिठाई",
    jam: "जैम बनाना",

    // Time
    hours: "घंटे",
    today: "आज",
    tomorrow: "कल",

    // Stats
    kgSaved: "किलो बचाया",
    dealsCompleted: "डील पूरी हुई",
    happyCustomers: "खुश ग्राहक",
    co2Reduced: "किलो CO₂ कम किया",

    // Messages
    dealPublished: "आपकी रेस्क्यू डील अब लाइव है!",
    thankYou: "खाना बचाने के लिए धन्यवाद!",

    // Profile
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    editProfile: "प्रोफाइल संपादित करें",
  },
  mr: {
    appName: "टेरालूप",
    tagline: "अन्न वाचवा, पैसे वाचवा, पृथ्वी वाचवा",
    welcomeMessage: "टेरालूप मध्ये आपले स्वागत आहे",
    selectLanguage: "तुमची पसंतीची भाषा निवडा",
    continue: "पुढे",
    back: "मागे",
    submit: "सबमिट करा",
    cancel: "रद्द करा",
    save: "जतन करा",
    loginTitle: "चळवळीत सामील व्हा",
    loginSubtitle: "तुमच्या समुदायात अन्न वाया जाणे कमी करण्यात मदत करा",
    enterName: "तुमचे नाव टाका",
    enterPhone: "तुमचा फोन नंबर टाका",
    namePlaceholder: "तुमचे पूर्ण नाव",
    phonePlaceholder: "10 अंकी मोबाइल नंबर",
    selectRole: "तुम्ही टेरालूप कसे वापरू इच्छिता?",
    iAmGrocer: "मी दुकानदार आहे",
    iAmBuyer: "मी खरेदीदार आहे",
    grocerDesc: "रेस्क्यू डील लिस्ट करा आणि अन्न वाया जाण्यापासून वाचवा",
    buyerDesc: "जवळपास ताज्या उत्पादनांवर उत्तम सौदे शोधा",
    grocerDashboard: "दुकानदार डॅशबोर्ड",
    addNewDeal: "रेस्क्यू डील जोडा",
    myListings: "माझ्या यादी",
    takePhoto: "फोटो घ्या किंवा अपलोड करा",
    analyzing: "AI तुमच्या फळाचे विश्लेषण करत आहे...",
    fruitDetected: "फळ ओळखले",
    recommendedPrice: "AI शिफारस केलेली किंमत",
    adjustPrice: "किंमत समायोजित करा",
    publishDeal: "रेस्क्यू डील प्रकाशित करा",
    quantity: "प्रमाण",
    bestFor: "सर्वोत्तम साठी",
    expiresIn: "यापूर्वी सर्वोत्तम",
    condition: "स्थिती",
    originalPrice: "मूळ किंमत",
    yourPrice: "तुमची किंमत",
    discount: "सवलत",
    buyerDashboard: "जवळपास ताज्या डील",
    availableDeals: "उपलब्ध रेस्क्यू डील",
    noDeals: "सध्या कोणतेही सौदे उपलब्ध नाहीत",
    buyNow: "आता रेस्क्यू करा",
    viewDetails: "तपशील पहा",
    contactGrocer: "दुकानदाराशी संपर्क साधा",
    yourBadges: "तुमचे बॅज",
    yourProgress: "तुमची प्रगती",
    pointsEarned: "मिळवलेले गुण",
    itemsSold: "विकलेल्या वस्तू",
    itemsBought: "रेस्क्यू केलेल्या वस्तू",
    foodSaved: "वाचवलेले अन्न",
    level: "पातळी",
    nextBadge: "पुढील बॅज",
    badgeFirstSale: "पहिली विक्री",
    badgeFirstSaleDesc: "तुमची पहिली रेस्क्यू वस्तू विकली",
    badgeFoodHero: "फूड हिरो",
    badgeFoodHeroDesc: "10 किलो अन्न वाया जाण्यापासून वाचवले",
    badgeRescueChamp: "रेस्क्यू चॅम्पियन",
    badgeRescueChampDesc: "25 वस्तू रेस्क्यू केल्या",
    badgeEcoWarrior: "इको वॉरियर",
    badgeEcoWarriorDesc: "50 किलो अन्न वाचवले",
    badgeSuperSeller: "सुपर सेलर",
    badgeSuperSellerDesc: "50 रेस्क्यू वस्तू विकल्या",
    badgeStreakMaster: "स्ट्रीक मास्टर",
    badgeStreakMasterDesc: "7 दिवसांची सक्रिय स्ट्रीक",
    mango: "आंबा",
    banana: "केळे",
    apple: "सफरचंद",
    orange: "संत्रा",
    papaya: "पपई",
    grapes: "द्राक्षे",
    watermelon: "कलिंगड",
    pomegranate: "डाळिंब",
    guava: "पेरू",
    pineapple: "अननस",
    ripe: "पिकलेले आणि गोड",
    veryRipe: "खूप पिकलेले",
    slightlyOverripe: "थोडे जास्त पिकलेले",
    perfectForShakes: "शेकसाठी उत्तम",
    shakes: "शेक",
    smoothies: "स्मूदी",
    cooking: "स्वयंपाक",
    eating: "ताजे खाणे",
    juice: "ताजा रस",
    desserts: "गोड पदार्थ",
    jam: "जाम बनवणे",
    hours: "तास",
    today: "आज",
    tomorrow: "उद्या",
    kgSaved: "किलो वाचवले",
    dealsCompleted: "सौदे पूर्ण",
    happyCustomers: "आनंदी ग्राहक",
    co2Reduced: "किलो CO₂ कमी केले",
    dealPublished: "तुमची रेस्क्यू डील आता लाइव्ह आहे!",
    thankYou: "अन्न वाचवल्याबद्दल धन्यवाद!",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    logout: "लॉगआउट",
    editProfile: "प्रोफाइल संपादित करा",
  },
  ta: {
    appName: "டெரா லூப்",
    tagline: "உணவைக் காப்பாற்றுங்கள், பணத்தைச் சேமியுங்கள், பூமியைக் காப்பாற்றுங்கள்",
    welcomeMessage: "டெரா லூப்-க்கு வரவேற்கிறோம்",
    selectLanguage: "உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்",
    continue: "தொடரவும்",
    back: "பின்",
    submit: "சமர்ப்பிக்கவும்",
    cancel: "ரத்து செய்",
    save: "சேமி",
    loginTitle: "இயக்கத்தில் சேரவும்",
    loginSubtitle: "உங்கள் சமூகத்தில் உணவு வீணாவதைக் குறைக்க உதவுங்கள்",
    enterName: "உங்கள் பெயரை உள்ளிடவும்",
    enterPhone: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    namePlaceholder: "உங்கள் முழு பெயர்",
    phonePlaceholder: "10 இலக்க மொபைல் எண்",
    selectRole: "டெரா லூப்-ஐ எவ்வாறு பயன்படுத்த விரும்புகிறீர்கள்?",
    iAmGrocer: "நான் மளிகைக்காரன்",
    iAmBuyer: "நான் வாங்குபவர்",
    grocerDesc: "மீட்பு ஒப்பந்தங்களைப் பட்டியலிட்டு உணவை வீணாகாமல் காப்பாற்றுங்கள்",
    buyerDesc: "அருகிலுள்ள புதிய தயாரிப்புகளில் சிறந்த ஒப்பந்தங்களைக் கண்டறியவும்",
    grocerDashboard: "மளிகைக்காரர் டாஷ்போர்டு",
    addNewDeal: "மீட்பு ஒப்பந்தத்தைச் சேர்க்கவும்",
    myListings: "எனது பட்டியல்கள்",
    takePhoto: "புகைப்படம் எடுக்கவும் அல்லது பதிவேற்றவும்",
    analyzing: "AI உங்கள் பழத்தை பகுப்பாய்வு செய்கிறது...",
    fruitDetected: "பழம் கண்டறியப்பட்டது",
    recommendedPrice: "AI பரிந்துரைக்கப்பட்ட விலை",
    adjustPrice: "விலையை சரிசெய்யவும்",
    publishDeal: "மீட்பு ஒப்பந்தத்தை வெளியிடவும்",
    quantity: "அளவு",
    bestFor: "சிறந்தது",
    expiresIn: "இதற்கு முன் சிறந்தது",
    condition: "நிலை",
    originalPrice: "அசல் விலை",
    yourPrice: "உங்கள் விலை",
    discount: "தள்ளுபடி",
    buyerDashboard: "அருகிலுள்ள புதிய ஒப்பந்தங்கள்",
    availableDeals: "கிடைக்கும் மீட்பு ஒப்பந்தங்கள்",
    noDeals: "இப்போது ஒப்பந்தங்கள் இல்லை",
    buyNow: "இப்போது மீட்கவும்",
    viewDetails: "விவரங்களைக் காண்க",
    contactGrocer: "மளிகைக்காரரைத் தொடர்பு கொள்ளவும்",
    yourBadges: "உங்கள் பேட்ஜ்கள்",
    yourProgress: "உங்கள் முன்னேற்றம்",
    pointsEarned: "பெற்ற புள்ளிகள்",
    itemsSold: "விற்கப்பட்ட பொருட்கள்",
    itemsBought: "மீட்கப்பட்ட பொருட்கள்",
    foodSaved: "சேமித்த உணவு",
    level: "நிலை",
    nextBadge: "அடுத்த பேட்ஜ்",
    badgeFirstSale: "முதல் விற்பனை",
    badgeFirstSaleDesc: "உங்கள் முதல் மீட்பு பொருளை விற்றீர்கள்",
    badgeFoodHero: "உணவு ஹீரோ",
    badgeFoodHeroDesc: "10 கிலோ உணவை வீணாகாமல் காப்பாற்றினீர்கள்",
    badgeRescueChamp: "மீட்பு சாம்பியன்",
    badgeRescueChampDesc: "25 பொருட்களை மீட்டெடுத்தீர்கள்",
    badgeEcoWarrior: "சுற்றுச்சூழல் போராளி",
    badgeEcoWarriorDesc: "50 கிலோ உணவைச் சேமித்தீர்கள்",
    badgeSuperSeller: "சூப்பர் விற்பனையாளர்",
    badgeSuperSellerDesc: "50 மீட்பு பொருட்களை விற்றீர்கள்",
    badgeStreakMaster: "ஸ்ட்ரீக் மாஸ்டர்",
    badgeStreakMasterDesc: "7 நாள் செயலில் ஸ்ட்ரீக்",
    mango: "மாம்பழம்",
    banana: "வாழைப்பழம்",
    apple: "ஆப்பிள்",
    orange: "ஆரஞ்சு",
    papaya: "பப்பாளி",
    grapes: "திராட்சை",
    watermelon: "தர்பூசணி",
    pomegranate: "மாதுளை",
    guava: "கொய்யா",
    pineapple: "அன்னாசி",
    ripe: "பழுத்த & இனிப்பான",
    veryRipe: "மிகவும் பழுத்த",
    slightlyOverripe: "சற்று அதிகமாக பழுத்த",
    perfectForShakes: "ஷேக்களுக்கு சரியானது",
    shakes: "ஷேக்ஸ்",
    smoothies: "ஸ்மூதிஸ்",
    cooking: "சமையல்",
    eating: "புதியதாக சாப்பிடுதல்",
    juice: "புதிய ஜூஸ்",
    desserts: "இனிப்புகள்",
    jam: "ஜாம் செய்தல்",
    hours: "மணி நேரம்",
    today: "இன்று",
    tomorrow: "நாளை",
    kgSaved: "கிலோ சேமித்தது",
    dealsCompleted: "ஒப்பந்தங்கள் நிறைவேறின",
    happyCustomers: "மகிழ்ச்சியான வாடிக்கையாளர்கள்",
    co2Reduced: "கிலோ CO₂ குறைந்தது",
    dealPublished: "உங்கள் மீட்பு ஒப்பந்தம் இப்போது நேரடியாக உள்ளது!",
    thankYou: "உணவைச் சேமித்ததற்கு நன்றி!",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    editProfile: "சுயவிவரத்தைத் திருத்து",
  },
  te: {
    appName: "టెర్రాలూప్",
    tagline: "ఆహారాన్ని ఆదా చేయండి, డబ్బును ఆదా చేయండి, భూమిని ఆదా చేయండి",
    welcomeMessage: "టెర్రాలూప్‌కు స్వాగతం",
    selectLanguage: "మీ ప్రాధాన్య భాషను ఎంచుకోండి",
    continue: "కొనసాగించు",
    back: "వెనుకకు",
    submit: "సమర్పించు",
    cancel: "రద్దు చేయి",
    save: "సేవ్ చేయి",
    loginTitle: "ఉద్యమంలో చేరండి",
    loginSubtitle: "మీ సమాజంలో ఆహార వృధాను తగ్గించడంలో సహాయం చేయండి",
    enterName: "మీ పేరు నమోదు చేయండి",
    enterPhone: "మీ ఫోన్ నంబర్ నమోదు చేయండి",
    namePlaceholder: "మీ పూర్తి పేరు",
    phonePlaceholder: "10 అంకెల మొబైల్ నంబర్",
    selectRole: "మీరు టెర్రాలూప్‌ని ఎలా ఉపయోగించాలనుకుంటున్నారు?",
    iAmGrocer: "నేను దుకాణదారుడిని",
    iAmBuyer: "నేను కొనుగోలుదారుని",
    grocerDesc: "రెస్క్యూ డీల్స్ జాబితా చేసి ఆహారాన్ని వృధా అవ్వకుండా కాపాడండి",
    buyerDesc: "సమీపంలోని తాజా ఉత్పత్తులపై గొప్ప డీల్స్ కనుగొనండి",
    grocerDashboard: "దుకాణదారు డాష్‌బోర్డ్",
    addNewDeal: "రెస్క్యూ డీల్ జోడించండి",
    myListings: "నా లిస్టింగ్‌లు",
    takePhoto: "ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి",
    analyzing: "AI మీ పండును విశ్లేషిస్తోంది...",
    fruitDetected: "పండు గుర్తించబడింది",
    recommendedPrice: "AI సిఫార్సు చేసిన ధర",
    adjustPrice: "ధరను సర్దుబాటు చేయండి",
    publishDeal: "రెస్క్యూ డీల్ ప్రచురించండి",
    quantity: "పరిమాణం",
    bestFor: "దీనికి ఉత్తమం",
    expiresIn: "దీని ముందు ఉత్తమం",
    condition: "పరిస్థితి",
    originalPrice: "అసలు ధర",
    yourPrice: "మీ ధర",
    discount: "డిస్కౌంట్",
    buyerDashboard: "సమీపంలో తాజా డీల్స్",
    availableDeals: "అందుబాటులో ఉన్న రెస్క్యూ డీల్స్",
    noDeals: "ప్రస్తుతం డీల్స్ అందుబాటులో లేవు",
    buyNow: "ఇప్పుడే రెస్క్యూ చేయండి",
    viewDetails: "వివరాలు చూడండి",
    contactGrocer: "దుకాణదారుని సంప్రదించండి",
    yourBadges: "మీ బ్యాడ్జ్‌లు",
    yourProgress: "మీ పురోగతి",
    pointsEarned: "సంపాదించిన పాయింట్లు",
    itemsSold: "అమ్మిన వస్తువులు",
    itemsBought: "రెస్క్యూ చేసిన వస్తువులు",
    foodSaved: "ఆదా చేసిన ఆహారం",
    level: "స్థాయి",
    nextBadge: "తదుపరి బ్యాడ్జ్",
    badgeFirstSale: "మొదటి అమ్మకం",
    badgeFirstSaleDesc: "మీ మొదటి రెస్క్యూ వస్తువును అమ్మారు",
    badgeFoodHero: "ఫుడ్ హీరో",
    badgeFoodHeroDesc: "10 కిలోల ఆహారాన్ని వృధా అవ్వకుండా కాపాడారు",
    badgeRescueChamp: "రెస్క్యూ ఛాంపియన్",
    badgeRescueChampDesc: "25 వస్తువులను రెస్క్యూ చేశారు",
    badgeEcoWarrior: "ఎకో వారియర్",
    badgeEcoWarriorDesc: "50 కిలోల ఆహారాన్ని ఆదా చేశారు",
    badgeSuperSeller: "సూపర్ సెల్లర్",
    badgeSuperSellerDesc: "50 రెస్క్యూ వస్తువులను అమ్మారు",
    badgeStreakMaster: "స్ట్రీక్ మాస్టర్",
    badgeStreakMasterDesc: "7 రోజుల యాక్టివ్ స్ట్రీక్",
    mango: "మామిడి",
    banana: "అరటి",
    apple: "ఆపిల్",
    orange: "నారింజ",
    papaya: "బొప్పాయి",
    grapes: "ద్రాక్ష",
    watermelon: "పుచ్చకాయ",
    pomegranate: "దానిమ్మ",
    guava: "జామ",
    pineapple: "అనాస",
    ripe: "పక్వమైన & తీపి",
    veryRipe: "చాలా పక్వమైన",
    slightlyOverripe: "కొంచెం ఎక్కువగా పక్వమైన",
    perfectForShakes: "షేక్‌లకు సరైనది",
    shakes: "షేక్స్",
    smoothies: "స్మూతీస్",
    cooking: "వంట",
    eating: "తాజాగా తినడం",
    juice: "తాజా జ్యూస్",
    desserts: "డెజర్ట్స్",
    jam: "జామ్ తయారీ",
    hours: "గంటలు",
    today: "ఈరోజు",
    tomorrow: "రేపు",
    kgSaved: "కిలోలు ఆదా",
    dealsCompleted: "డీల్స్ పూర్తయ్యాయి",
    happyCustomers: "సంతోషకరమైన కస్టమర్లు",
    co2Reduced: "కిలోలు CO₂ తగ్గింది",
    dealPublished: "మీ రెస్క్యూ డీల్ ఇప్పుడు లైవ్‌లో ఉంది!",
    thankYou: "ఆహారాన్ని ఆదా చేసినందుకు ధన్యవాదాలు!",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్స్",
    logout: "లాగ్‌అవుట్",
    editProfile: "ప్రొఫైల్ సవరించు",
  },
  bn: {
    appName: "টেরালুপ",
    tagline: "খাবার বাঁচান, টাকা বাঁচান, পৃথিবী বাঁচান",
    welcomeMessage: "টেরালুপে স্বাগতম",
    selectLanguage: "আপনার পছন্দের ভাষা নির্বাচন করুন",
    continue: "চালিয়ে যান",
    back: "পিছনে",
    submit: "জমা দিন",
    cancel: "বাতিল",
    save: "সংরক্ষণ",
    loginTitle: "আন্দোলনে যোগ দিন",
    loginSubtitle: "আপনার সম্প্রদায়ে খাবার অপচয় কমাতে সাহায্য করুন",
    enterName: "আপনার নাম লিখুন",
    enterPhone: "আপনার ফোন নম্বর লিখুন",
    namePlaceholder: "আপনার পুরো নাম",
    phonePlaceholder: "১০ সংখ্যার মোবাইল নম্বর",
    selectRole: "আপনি টেরালুপ কীভাবে ব্যবহার করতে চান?",
    iAmGrocer: "আমি দোকানদার",
    iAmBuyer: "আমি ক্রেতা",
    grocerDesc: "রেসকিউ ডিল তালিকাভুক্ত করুন এবং খাবার নষ্ট হওয়া থেকে বাঁচান",
    buyerDesc: "কাছাকাছি তাজা পণ্যে দুর্দান্ত ডিল খুঁজুন",
    grocerDashboard: "দোকানদার ড্যাশবোর্ড",
    addNewDeal: "রেসকিউ ডিল যোগ করুন",
    myListings: "আমার তালিকা",
    takePhoto: "ছবি তুলুন বা আপলোড করুন",
    analyzing: "AI আপনার ফল বিশ্লেষণ করছে...",
    fruitDetected: "ফল সনাক্ত হয়েছে",
    recommendedPrice: "AI প্রস্তাবিত মূল্য",
    adjustPrice: "মূল্য সামঞ্জস্য করুন",
    publishDeal: "রেসকিউ ডিল প্রকাশ করুন",
    quantity: "পরিমাণ",
    bestFor: "এর জন্য সেরা",
    expiresIn: "এর আগে সেরা",
    condition: "অবস্থা",
    originalPrice: "আসল মূল্য",
    yourPrice: "আপনার মূল্য",
    discount: "ছাড়",
    buyerDashboard: "কাছাকাছি তাজা ডিল",
    availableDeals: "উপলব্ধ রেসকিউ ডিল",
    noDeals: "এখন কোনো ডিল নেই",
    buyNow: "এখনই রেসকিউ করুন",
    viewDetails: "বিস্তারিত দেখুন",
    contactGrocer: "দোকানদারের সাথে যোগাযোগ করুন",
    yourBadges: "আপনার ব্যাজ",
    yourProgress: "আপনার অগ্রগতি",
    pointsEarned: "অর্জিত পয়েন্ট",
    itemsSold: "বিক্রিত আইটেম",
    itemsBought: "রেসকিউ করা আইটেম",
    foodSaved: "সংরক্ষিত খাবার",
    level: "স্তর",
    nextBadge: "পরবর্তী ব্যাজ",
    badgeFirstSale: "প্রথম বিক্রি",
    badgeFirstSaleDesc: "আপনার প্রথম রেসকিউ আইটেম বিক্রি করেছেন",
    badgeFoodHero: "ফুড হিরো",
    badgeFoodHeroDesc: "১০ কেজি খাবার নষ্ট হওয়া থেকে বাঁচিয়েছেন",
    badgeRescueChamp: "রেসকিউ চ্যাম্পিয়ন",
    badgeRescueChampDesc: "২৫টি আইটেম রেসকিউ করেছেন",
    badgeEcoWarrior: "ইকো ওয়ারিয়র",
    badgeEcoWarriorDesc: "৫০ কেজি খাবার সংরক্ষণ করেছেন",
    badgeSuperSeller: "সুপার সেলার",
    badgeSuperSellerDesc: "৫০টি রেসকিউ আইটেম বিক্রি করেছেন",
    badgeStreakMaster: "স্ট্রিক মাস্টার",
    badgeStreakMasterDesc: "৭ দিনের সক্রিয় স্ট্রিক",
    mango: "আম",
    banana: "কলা",
    apple: "আপেল",
    orange: "কমলা",
    papaya: "পেঁপে",
    grapes: "আঙুর",
    watermelon: "তরমুজ",
    pomegranate: "ডালিম",
    guava: "পেয়ারা",
    pineapple: "আনারস",
    ripe: "পাকা ও মিষ্টি",
    veryRipe: "খুব পাকা",
    slightlyOverripe: "সামান্য বেশি পাকা",
    perfectForShakes: "শেকের জন্য উপযুক্ত",
    shakes: "শেক",
    smoothies: "স্মুদি",
    cooking: "রান্না",
    eating: "তাজা খাওয়া",
    juice: "তাজা জুস",
    desserts: "মিষ্টি",
    jam: "জ্যাম তৈরি",
    hours: "ঘণ্টা",
    today: "আজ",
    tomorrow: "আগামীকাল",
    kgSaved: "কেজি সংরক্ষিত",
    dealsCompleted: "ডিল সম্পন্ন",
    happyCustomers: "সন্তুষ্ট গ্রাহক",
    co2Reduced: "কেজি CO₂ হ্রাস",
    dealPublished: "আপনার রেসকিউ ডিল এখন লাইভ!",
    thankYou: "খাবার সংরক্ষণের জন্য ধন্যবাদ!",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    logout: "লগআউট",
    editProfile: "প্রোফাইল সম্পাদনা",
  },
  gu: {
    appName: "ટેરાલૂપ",
    tagline: "ખોરાક બચાવો, પૈસા બચાવો, પૃથ્વી બચાવો",
    welcomeMessage: "ટેરાલૂપમાં આપનું સ્વાગત છે",
    selectLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    continue: "ચાલુ રાખો",
    back: "પાછા",
    submit: "સબમિટ કરો",
    cancel: "રદ કરો",
    save: "સાચવો",
    loginTitle: "ચળવળમાં જોડાઓ",
    loginSubtitle: "તમારા સમુદાયમાં ખોરાકનો બગાડ ઘટાડવામાં મદદ કરો",
    enterName: "તમારું નામ દાખલ કરો",
    enterPhone: "તમારો ફોન નંબર દાખલ કરો",
    namePlaceholder: "તમારું પૂરું નામ",
    phonePlaceholder: "10 અંકનો મોબાઇલ નંબર",
    selectRole: "તમે ટેરાલૂપનો ઉપયોગ કેવી રીતે કરવા માંગો છો?",
    iAmGrocer: "હું દુકાનદાર છું",
    iAmBuyer: "હું ખરીદનાર છું",
    grocerDesc: "રેસ્ક્યુ ડીલ લિસ્ટ કરો અને ખોરાકને બગાડથી બચાવો",
    buyerDesc: "નજીકમાં તાજા ઉત્પાદનો પર સરસ ડીલ શોધો",
    grocerDashboard: "દુકાનદાર ડેશબોર્ડ",
    addNewDeal: "રેસ્ક્યુ ડીલ ઉમેરો",
    myListings: "મારી યાદી",
    takePhoto: "ફોટો લો અથવા અપલોડ કરો",
    analyzing: "AI તમારા ફળનું વિશ્લેષણ કરી રહ્યું છે...",
    fruitDetected: "ફળ ઓળખાયું",
    recommendedPrice: "AI ભલામણ કરેલ કિંમત",
    adjustPrice: "કિંમત ગોઠવો",
    publishDeal: "રેસ્ક્યુ ડીલ પ્રકાશિત કરો",
    quantity: "જથ્થો",
    bestFor: "માટે શ્રેષ્ઠ",
    expiresIn: "પહેલા શ્રેષ્ઠ",
    condition: "સ્થિતિ",
    originalPrice: "મૂળ કિંમત",
    yourPrice: "તમારી કિંમત",
    discount: "ડિસ્કાઉન્ટ",
    buyerDashboard: "નજીકમાં તાજી ડીલ",
    availableDeals: "ઉપલબ્ધ રેસ્ક્યુ ડીલ",
    noDeals: "અત્યારે કોઈ ડીલ ઉપલબ્ધ નથી",
    buyNow: "હમણાં રેસ્ક્યુ કરો",
    viewDetails: "વિગતો જુઓ",
    contactGrocer: "દુકાનદારનો સંપર્ક કરો",
    yourBadges: "તમારા બેજ",
    yourProgress: "તમારી પ્રગતિ",
    pointsEarned: "મેળવેલ પોઈન્ટ",
    itemsSold: "વેચાયેલ આઇટમ",
    itemsBought: "રેસ્ક્યુ કરેલ આઇટમ",
    foodSaved: "બચાવેલ ખોરાક",
    level: "સ્તર",
    nextBadge: "આગળનું બેજ",
    badgeFirstSale: "પ્રથમ વેચાણ",
    badgeFirstSaleDesc: "તમારી પ્રથમ રેસ્ક્યુ આઇટમ વેચી",
    badgeFoodHero: "ફૂડ હીરો",
    badgeFoodHeroDesc: "10 કિલો ખોરાક બગાડથી બચાવ્યો",
    badgeRescueChamp: "રેસ્ક્યુ ચેમ્પિયન",
    badgeRescueChampDesc: "25 આઇટમ રેસ્ક્યુ કર્યા",
    badgeEcoWarrior: "ઇકો વોરિયર",
    badgeEcoWarriorDesc: "50 કિલો ખોરાક બચાવ્યો",
    badgeSuperSeller: "સુપર સેલર",
    badgeSuperSellerDesc: "50 રેસ્ક્યુ આઇટમ વેચ્યા",
    badgeStreakMaster: "સ્ટ્રીક માસ્ટર",
    badgeStreakMasterDesc: "7 દિવસની સક્રિય સ્ટ્રીક",
    mango: "કેરી",
    banana: "કેળા",
    apple: "સફરજન",
    orange: "નારંગી",
    papaya: "પપૈયું",
    grapes: "દ્રાક્ષ",
    watermelon: "તરબૂચ",
    pomegranate: "દાડમ",
    guava: "જામફળ",
    pineapple: "અનાનસ",
    ripe: "પાકેલું અને મીઠું",
    veryRipe: "ખૂબ પાકેલું",
    slightlyOverripe: "થોડું વધુ પાકેલું",
    perfectForShakes: "શેક માટે ઉત્તમ",
    shakes: "શેક",
    smoothies: "સ્મૂધી",
    cooking: "રસોઈ",
    eating: "તાજું ખાવું",
    juice: "તાજો રસ",
    desserts: "મીઠાઈ",
    jam: "જામ બનાવવું",
    hours: "કલાક",
    today: "આજે",
    tomorrow: "આવતીકાલે",
    kgSaved: "કિલો બચાવ્યું",
    dealsCompleted: "ડીલ પૂર્ણ",
    happyCustomers: "ખુશ ગ્રાહકો",
    co2Reduced: "કિલો CO₂ ઘટાડ્યું",
    dealPublished: "તમારી રેસ્ક્યુ ડીલ હવે લાઇવ છે!",
    thankYou: "ખોરાક બચાવવા બદલ આભાર!",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    logout: "લૉગઆઉટ",
    editProfile: "પ્રોફાઇલ સંપાદિત કરો",
  },
  kn: {
    appName: "ಟೆರಾಲೂಪ್",
    tagline: "ಆಹಾರ ಉಳಿಸಿ, ಹಣ ಉಳಿಸಿ, ಭೂಮಿಯನ್ನು ಉಳಿಸಿ",
    welcomeMessage: "ಟೆರಾಲೂಪ್‌ಗೆ ಸ್ವಾಗತ",
    selectLanguage: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    back: "ಹಿಂದೆ",
    submit: "ಸಲ್ಲಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    save: "ಉಳಿಸಿ",
    loginTitle: "ಚಳುವಳಿಗೆ ಸೇರಿ",
    loginSubtitle: "ನಿಮ್ಮ ಸಮುದಾಯದಲ್ಲಿ ಆಹಾರ ವ್ಯರ್ಥವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಸಹಾಯ ಮಾಡಿ",
    enterName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    enterPhone: "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    namePlaceholder: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು",
    phonePlaceholder: "10 ಅಂಕಿ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    selectRole: "ನೀವು ಟೆರಾಲೂಪ್ ಅನ್ನು ಹೇಗೆ ಬಳಸಲು ಬಯಸುತ್ತೀರಿ?",
    iAmGrocer: "ನಾನು ಅಂಗಡಿಕಾರ",
    iAmBuyer: "ನಾನು ಖರೀದಿದಾರ",
    grocerDesc: "ರೆಸ್ಕ್ಯೂ ಡೀಲ್‌ಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ ಮತ್ತು ಆಹಾರವನ್ನು ವ್ಯರ್ಥದಿಂದ ಉಳಿಸಿ",
    buyerDesc: "ಹತ್ತಿರದ ತಾಜಾ ಉತ್ಪನ್ನಗಳ ಮೇಲೆ ಉತ್ತಮ ಡೀಲ್‌ಗಳನ್ನು ಹುಡುಕಿ",
    grocerDashboard: "ಅಂಗಡಿಕಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    addNewDeal: "ರೆಸ್ಕ್ಯೂ ಡೀಲ್ ಸೇರಿಸಿ",
    myListings: "ನನ್ನ ಪಟ್ಟಿಗಳು",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    analyzing: "AI ನಿಮ್ಮ ಹಣ್ಣನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    fruitDetected: "ಹಣ್ಣು ಪತ್ತೆಯಾಗಿದೆ",
    recommendedPrice: "AI ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಲೆ",
    adjustPrice: "ಬೆಲೆ ಹೊಂದಿಸಿ",
    publishDeal: "ರೆಸ್ಕ್ಯೂ ಡೀಲ್ ಪ್ರಕಟಿಸಿ",
    quantity: "ಪ್ರಮಾಣ",
    bestFor: "ಇದಕ್ಕೆ ಉತ್ತಮ",
    expiresIn: "ಇದಕ್ಕೆ ಮೊದಲು ಉತ್ತಮ",
    condition: "ಸ್ಥಿತಿ",
    originalPrice: "ಮೂಲ ಬೆಲೆ",
    yourPrice: "ನಿಮ್ಮ ಬೆಲೆ",
    discount: "ರಿಯಾಯಿತಿ",
    buyerDashboard: "ಹತ್ತಿರದ ತಾಜಾ ಡೀಲ್‌ಗಳು",
    availableDeals: "ಲಭ್ಯವಿರುವ ರೆಸ್ಕ್ಯೂ ಡೀಲ್‌ಗಳು",
    noDeals: "ಈಗ ಯಾವುದೇ ಡೀಲ್‌ಗಳಿಲ್ಲ",
    buyNow: "ಈಗಲೇ ರೆಸ್ಕ್ಯೂ ಮಾಡಿ",
    viewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ",
    contactGrocer: "ಅಂಗಡಿಕಾರನನ್ನು ಸಂಪರ್ಕಿಸಿ",
    yourBadges: "ನಿಮ್ಮ ಬ್ಯಾಡ್ಜ್‌ಗಳು",
    yourProgress: "ನಿಮ್ಮ ಪ್ರಗತಿ",
    pointsEarned: "ಗಳಿಸಿದ ಪಾಯಿಂಟ್‌ಗಳು",
    itemsSold: "ಮಾರಾಟವಾದ ಐಟಂಗಳು",
    itemsBought: "ರೆಸ್ಕ್ಯೂ ಮಾಡಿದ ಐಟಂಗಳು",
    foodSaved: "ಉಳಿಸಿದ ಆಹಾರ",
    level: "ಮಟ್ಟ",
    nextBadge: "ಮುಂದಿನ ಬ್ಯಾಡ್ಜ್",
    badgeFirstSale: "ಮೊದಲ ಮಾರಾಟ",
    badgeFirstSaleDesc: "ನಿಮ್ಮ ಮೊದಲ ರೆಸ್ಕ್ಯೂ ಐಟಂ ಮಾರಾಟ ಮಾಡಿದಿರಿ",
    badgeFoodHero: "ಫುಡ್ ಹೀರೋ",
    badgeFoodHeroDesc: "10 ಕೆಜಿ ಆಹಾರವನ್ನು ವ್ಯರ್ಥದಿಂದ ಉಳಿಸಿದಿರಿ",
    badgeRescueChamp: "ರೆಸ್ಕ್ಯೂ ಚಾಂಪಿಯನ್",
    badgeRescueChampDesc: "25 ಐಟಂಗಳನ್ನು ರೆಸ್ಕ್ಯೂ ಮಾಡಿದಿರಿ",
    badgeEcoWarrior: "ಇಕೋ ವಾರಿಯರ್",
    badgeEcoWarriorDesc: "50 ಕೆಜಿ ಆಹಾರ ಉಳಿಸಿದಿರಿ",
    badgeSuperSeller: "ಸೂಪರ್ ಸೆಲ್ಲರ್",
    badgeSuperSellerDesc: "50 ರೆಸ್ಕ್ಯೂ ಐಟಂಗಳನ್ನು ಮಾರಾಟ ಮಾಡಿದಿರಿ",
    badgeStreakMaster: "ಸ್ಟ್ರೀಕ್ ಮಾಸ್ಟರ್",
    badgeStreakMasterDesc: "7 ದಿನಗಳ ಸಕ್ರಿಯ ಸ್ಟ್ರೀಕ್",
    mango: "ಮಾವು",
    banana: "ಬಾಳೆಹಣ್ಣು",
    apple: "ಸೇಬು",
    orange: "ಕಿತ್ತಳೆ",
    papaya: "ಪಪ್ಪಾಯ",
    grapes: "ದ್ರಾಕ್ಷಿ",
    watermelon: "ಕಲ್ಲಂಗಡಿ",
    pomegranate: "ದಾಳಿಂಬೆ",
    guava: "ಪೇರಲ",
    pineapple: "ಅನಾನಸ್",
    ripe: "ಮಾಗಿದ ಮತ್ತು ಸಿಹಿ",
    veryRipe: "ತುಂಬಾ ಮಾಗಿದ",
    slightlyOverripe: "ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಮಾಗಿದ",
    perfectForShakes: "ಶೇಕ್‌ಗಳಿಗೆ ಪರಿಪೂರ್ಣ",
    shakes: "ಶೇಕ್ಸ್",
    smoothies: "ಸ್ಮೂತಿಗಳು",
    cooking: "ಅಡುಗೆ",
    eating: "ತಾಜಾ ತಿನ್ನುವುದು",
    juice: "ತಾಜಾ ಜ್ಯೂಸ್",
    desserts: "ಸಿಹಿತಿಂಡಿಗಳು",
    jam: "ಜಾಮ್ ಮಾಡುವುದು",
    hours: "ಗಂಟೆಗಳು",
    today: "ಇಂದು",
    tomorrow: "ನಾಳೆ",
    kgSaved: "ಕೆಜಿ ಉಳಿಸಲಾಗಿದೆ",
    dealsCompleted: "ಡೀಲ್‌ಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ",
    happyCustomers: "ಸಂತೋಷದ ಗ್ರಾಹಕರು",
    co2Reduced: "ಕೆಜಿ CO₂ ಕಡಿಮೆಯಾಗಿದೆ",
    dealPublished: "ನಿಮ್ಮ ರೆಸ್ಕ್ಯೂ ಡೀಲ್ ಈಗ ಲೈವ್ ಆಗಿದೆ!",
    thankYou: "ಆಹಾರ ಉಳಿಸಿದ್ದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    logout: "ಲಾಗ್‌ಔಟ್",
    editProfile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
  },
}

const defaultBadges: Badge[] = [
  {
    id: "first-sale",
    name: "First Sale",
    nameKey: "badgeFirstSale",
    description: "Sold your first rescue item",
    descriptionKey: "badgeFirstSaleDesc",
    icon: "🌱",
    requirement: 1,
    type: "sold",
  },
  {
    id: "food-hero",
    name: "Food Hero",
    nameKey: "badgeFoodHero",
    description: "Saved 10kg of food from waste",
    descriptionKey: "badgeFoodHeroDesc",
    icon: "🦸",
    requirement: 10,
    type: "saved",
  },
  {
    id: "rescue-champ",
    name: "Rescue Champion",
    nameKey: "badgeRescueChamp",
    description: "Rescued 25 items",
    descriptionKey: "badgeRescueChampDesc",
    icon: "🏆",
    requirement: 25,
    type: "bought",
  },
  {
    id: "eco-warrior",
    name: "Eco Warrior",
    nameKey: "badgeEcoWarrior",
    description: "Saved 50kg of food",
    descriptionKey: "badgeEcoWarriorDesc",
    icon: "🌍",
    requirement: 50,
    type: "saved",
  },
  {
    id: "super-seller",
    name: "Super Seller",
    nameKey: "badgeSuperSeller",
    description: "Sold 50 rescue items",
    descriptionKey: "badgeSuperSellerDesc",
    icon: "⭐",
    requirement: 50,
    type: "sold",
  },
  {
    id: "streak-master",
    name: "Streak Master",
    nameKey: "badgeStreakMaster",
    description: "7-day active streak",
    descriptionKey: "badgeStreakMasterDesc",
    icon: "🔥",
    requirement: 7,
    type: "streak",
  },
]

const AppContext = createContext<AppContextType | undefined>(undefined)

export function AppProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [user, setUser] = useState<User | null>(null)
  const [listings, setListings] = useState<FruitListing[]>([])
  const [currentStep, setCurrentStep] = useState<"language" | "login" | "role" | "dashboard">("language")

  // Load sample listings for demo
  useEffect(() => {
    const sampleListings: FruitListing[] = [
      {
        id: "1",
        grocerId: "grocer-1",
        grocerName: "Ramesh Fruits",
        grocerPhone: "9876543210",
        fruitName: "Mango",
        fruitNameKey: "mango",
        condition: "Perfect for Shakes",
        conditionKey: "perfectForShakes",
        recommendedPrice: 40,
        finalPrice: 35,
        originalPrice: 80,
        quantity: "2",
        unit: "kg",
        imageUrl: "/ripe-golden-mango-fruit.jpg",
        bestFor: ["Shakes", "Smoothies", "Aamras"],
        bestForKeys: ["shakes", "smoothies"],
        expiresIn: "Today",
        createdAt: new Date(),
        status: "active",
      },
      {
        id: "2",
        grocerId: "grocer-2",
        grocerName: "Fresh Mart",
        grocerPhone: "9876543211",
        fruitName: "Banana",
        fruitNameKey: "banana",
        condition: "Very Ripe",
        conditionKey: "veryRipe",
        recommendedPrice: 25,
        finalPrice: 20,
        originalPrice: 50,
        quantity: "1",
        unit: "dozen",
        imageUrl: "/ripe-yellow-bananas-bunch.jpg",
        bestFor: ["Smoothies", "Cooking", "Desserts"],
        bestForKeys: ["smoothies", "cooking", "desserts"],
        expiresIn: "12 hours",
        createdAt: new Date(),
        status: "active",
      },
      {
        id: "3",
        grocerId: "grocer-3",
        grocerName: "Green Valley",
        grocerPhone: "9876543212",
        fruitName: "Papaya",
        fruitNameKey: "papaya",
        condition: "Ripe & Sweet",
        conditionKey: "ripe",
        recommendedPrice: 30,
        finalPrice: 25,
        originalPrice: 60,
        quantity: "1",
        unit: "piece",
        imageUrl: "/ripe-orange-papaya-fruit-cut.jpg",
        bestFor: ["Fresh Eating", "Juice", "Salad"],
        bestForKeys: ["eating", "juice"],
        expiresIn: "Tomorrow",
        createdAt: new Date(),
        status: "active",
      },
    ]
    setListings(sampleListings)
  }, [])

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  const addListing = (listing: FruitListing) => {
    setListings((prev) => [listing, ...prev])
    if (user) {
      setUser({
        ...user,
        itemsSold: user.itemsSold + 1,
        points: user.points + 50,
        foodSaved: user.foodSaved + Number.parseFloat(listing.quantity),
      })
    }
  }

  const updateListing = (id: string, updates: Partial<FruitListing>) => {
    setListings((prev) => prev.map((l) => (l.id === id ? { ...l, ...updates } : l)))
  }

  const purchaseListing = (listingId: string) => {
    const listing = listings.find((l) => l.id === listingId)
    if (!listing || !user) return

    updateListing(listingId, { status: "sold" })
    setUser({
      ...user,
      itemsBought: user.itemsBought + 1,
      points: user.points + 30,
      foodSaved: user.foodSaved + Number.parseFloat(listing.quantity),
    })
  }

  return (
    <AppContext.Provider
      value={{
        language,
        setLanguage,
        user,
        setUser,
        listings,
        addListing,
        updateListing,
        purchaseListing,
        t,
        currentStep,
        setCurrentStep,
      }}
    >
      {children}
    </AppContext.Provider>
  )
}

export function useApp() {
  const context = useContext(AppContext)
  if (!context) {
    throw new Error("useApp must be used within AppProvider")
  }
  return context
}
